# Generated by Django 2.2.1 on 2019-12-16 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_pref', models.CharField(choices=[('1', 'English'), ('2', 'Arabic')], default='English', max_length=10)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(blank=True, max_length=70, null=True)),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user/profile/profile')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='user/profile/background')),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('mobile', models.CharField(max_length=200)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=200)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=15, null=True)),
                ('lat', models.CharField(blank=True, max_length=50, null=True)),
                ('lon', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('login_type', models.CharField(choices=[('1', 'Normal'), ('2', 'Facebook'), ('3', 'Google')], max_length=10)),
                ('social_id', models.CharField(blank=True, max_length=200, null=True)),
                ('device_type', models.CharField(choices=[('1', 'Android'), ('2', 'Ios'), ('3', 'Web')], max_length=10)),
                ('device_token', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('1', 'User'), ('2', 'Service Provider')], max_length=20)),
                ('has_dual_account', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ruser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otpuser', to='uaccounts.RegisteredUser')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foffer', to='offer.Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuser_offer', to='uaccounts.RegisteredUser')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteGarage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fgarage', to='saccounts.Garage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuser', to='uaccounts.RegisteredUser')),
            ],
        ),
    ]
