# Generated by Django 2.2.1 on 2020-01-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='ar_about',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='ar_area',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='ar_city',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='ar_country',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='ar_country_code',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='ar_first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='ar_last_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='ar_mobile',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='ar_street',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='ar_zipcode',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
