# Generated by Django 2.2.1 on 2020-03-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaccounts', '0002_auto_20200131_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('times_ago', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
