# Generated by Django 2.2.1 on 2020-03-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaccounts', '0004_remove_allnotifications_times_ago'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnotifications',
            name='heading',
            field=models.CharField(default='', max_length=100),
        ),
    ]
