# Generated by Django 2.2.1 on 2019-12-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extra', '0001_initial'),
        ('uaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unuser', to='uaccounts.RegisteredUser'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ManyToManyField(related_name='runot', through='extra.UserNotification', to='uaccounts.RegisteredUser'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('notification', 'user')},
        ),
    ]
