# Generated by Django 2.2.1 on 2019-12-16 14:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='serviceprovider/offer/image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='serviceprovider/offer/image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='serviceprovider/offer/image')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='serviceprovider/offer/image')),
                ('video1', models.FileField(blank=True, null=True, upload_to='serviceprovider/offer/video')),
                ('video1_thumbnail', models.ImageField(blank=True, default='', null=True, upload_to='serviceprovider/offer/video/thumbnail')),
                ('video2', models.FileField(blank=True, null=True, upload_to='serviceprovider/offer/video')),
                ('video2_thumbnail', models.ImageField(blank=True, default='', null=True, upload_to='serviceprovider/offer/video/thumbnail')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('coupon', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('advertisment_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_desc', models.CharField(max_length=800)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('valid_for', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlanKeyFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_feature', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_plan', to='offer.SubscriptionPlan')),
            ],
        ),
    ]
