# Generated by Django 2.2.1 on 2019-12-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        ('uaccounts', '0001_initial'),
        ('saccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='ruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_ruser', to='uaccounts.RegisteredUser'),
        ),
        migrations.AddField(
            model_name='subscriptionplankeyfeatures',
            name='spkf_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.SubscriptionPlan'),
        ),
        migrations.AddField(
            model_name='offer',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogarage', to='saccounts.Garage'),
        ),
    ]
