# Generated by Django 2.2.1 on 2019-12-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20191216_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_desc_ar',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_name_ar',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_ar',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='valid_for_ar',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplankeyfeatures',
            name='key_feature_ar',
            field=models.CharField(default='', max_length=400),
        ),
    ]
