# Generated by Django 2.2.1 on 2020-01-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_auto_20191219_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='ar_advertisment_license_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='offer',
            name='ar_coupon',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='ar_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='ar_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ar_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ar_valid_for',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
