# Generated by Django 2.2.1 on 2019-12-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('complaint', models.CharField(max_length=1000)),
                ('admin_message', models.CharField(default='', max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', '1'), ('Closed', '2'), ('Processing', '3')], default='Open', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store_image1', models.ImageField(blank=True, null=True, upload_to='serviceprovider/garage')),
                ('store_image2', models.ImageField(blank=True, null=True, upload_to='serviceprovider/garage')),
                ('store_image3', models.ImageField(blank=True, null=True, upload_to='serviceprovider/garage')),
                ('contact_person', models.CharField(max_length=70)),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=10)),
                ('contact_num', models.CharField(max_length=15)),
                ('tax_registration_num', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_registration_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_owner', models.BooleanField(default=True)),
                ('garage_rating', models.PositiveIntegerField(default=0)),
                ('slug1', models.SlugField(default='', max_length=100)),
                ('slug2', models.SlugField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=100)),
                ('subtype_ar', models.CharField(default='', max_length=200)),
                ('icon', models.ImageField(blank=True, default='serviceprovider/service_subtype/def_subcat.png', null=True, upload_to='serviceprovider/service_subtype')),
                ('slug', models.SlugField(default='', max_length=100)),
                ('slug_ar', models.SlugField(default='', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('subcategory_rating', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('type_ar', models.CharField(default='', max_length=200)),
                ('icon', models.ImageField(blank=True, default='serviceprovider/service_type/def_cat.png', null=True, upload_to='serviceprovider/service_type')),
                ('slug', models.SlugField(default='', max_length=100)),
                ('slug_ar', models.SlugField(default='', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category_rating', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TempGarageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='serviceprovider/temp')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='serviceprovider/service_type')),
                ('slug', models.SlugField(default='', max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('model_rating', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'sat'), ('2', 'sun'), ('3', 'mon'), ('4', 'tue'), ('5', 'wed'), ('6', 'thur'), ('7', 'fri')], max_length=10)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wsgarage', to='saccounts.Garage')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModleManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vmm_garage', to='saccounts.Garage')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vmm_model', to='saccounts.VehicleModle')),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rvgarage', to='saccounts.Garage')),
            ],
        ),
    ]
