# Generated by Django 2.2.1 on 2019-12-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0003_auto_20191217_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='admin_message_ar',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
