# Generated by Django 2.2.1 on 2020-01-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0004_customercomplaint_admin_message_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='ar_admin_message',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='ar_complaint',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='ar_email',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='ar_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='garage',
            name='ar_city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='garage',
            name='ar_contact_num',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='garage',
            name='ar_contact_person',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='garage',
            name='ar_country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='garage',
            name='ar_country_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='garage',
            name='ar_garage_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='garage',
            name='ar_location',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='garage',
            name='ar_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='garage',
            name='ar_slug1',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='garage',
            name='ar_slug2',
            field=models.SlugField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='garage',
            name='ar_state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='garage',
            name='ar_tax_registration_num',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='ar_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userreview',
            name='ar_review',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='ar_day',
            field=models.CharField(choices=[('1', 'sat'), ('2', 'sun'), ('3', 'mon'), ('4', 'tue'), ('5', 'wed'), ('6', 'thur'), ('7', 'fri')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='ar_end_time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='ar_start_time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
