# Generated by Django 2.2.1 on 2020-01-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20191216_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='ar_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='ar_status',
            field=models.CharField(choices=[('Completed', '1'), ('Declined', '2'), ('Cancelled', '3'), ('Pending', '4')], default='', max_length=10),
        ),
    ]
